version: 2
updates:
  # Enable version updates for npm in the frontend directory
  - package-ecosystem: "npm"
    # Look for `package.json` and `package-lock.json` in the `frontend` directory
    directory: "/frontend"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for Docker in the frontend directory (if applicable)
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `frontend` directory
    directory: "/frontend"
    # Check for updates once a week
    schedule:
      interval: "weekly"
